name: Deploy to EBS Develop Enviroment

on:
  push:
    branches:
      - develop
jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> "$GITHUB_OUTPUT"
        id: date
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Generate deployment package
        run: zip -r deploy.zip * .[^.]* -x "**node_modules**"

      - name: Beanstalk Deploy for app
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{secrets.ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.SECRET_ACCESS_KEY}}
          application_name: yeebam
          environment_name: yeebam-dev
          region: us-east-1
          version_label: "${{ steps.date.outputs.NOW }}-${{ github.sha }}"
          deployment_package: deploy.zip

      - name: Deployed!
        run: echo App deployed to ELB